# Generated by Django 5.0.6 on 2024-08-27 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('campaign', '0040_order_logistics_center_status'),
    ]

    # IMPORTNANT NOTE: the following migration was undone because we cannot
    # deploy it to the main environment at the time. for environment where this
    # migration hasn't been executed the operations are now commented so it
    # won't be, and for environments where this migration has been executed
    # migration version 0042 undos these
    # when the main envornment's data is ready for these constraints the model
    # change will be made again and a new migration will be created
    operations = [
        # migrations.AlterField(
        #     model_name='employee',
        #     name='auth_id',
        #     field=models.CharField(
        #         blank=True, max_length=255, null=True, unique=True
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name='employee',
        #     name='email',
        #     field=models.EmailField(
        #         blank=True, max_length=254, null=True, unique=True
        #     ),
        # ),
        # migrations.AlterField(
        #     model_name='employee',
        #     name='phone_number',
        #     field=models.CharField(
        #         blank=True,
        #         max_length=255,
        #         null=True,
        #         unique=True,
        #         validators=[lib.phone_utils.validate_phone_number],
        #     ),
        # ),
    ]
